export enum ProductScent {
  BERGAMOTA_ALEGRIM = "BERGAMOTA_ALEGRIM",
  MANGA_TANGERINA = "MANGA_TANGERINA",
  CHA_BRANCO = "CHA_BRANCO",
  CAFE_MARACUJA = "CAFE_MARACUJA",
  AMENDOAS_CANELA = "AMENDOAS_CANELA",
  CAPIM_VANILA = "CAPIM_VANILA",
}